[project]
name = "sagemtl"
version = "0.0.1"
description = "MTL pipeline: crawl -> clean -> translate"
authors = [{name = "Kheiven D'Haiti"}]
requires-python = ">=3.10"
dependencies = [
  "httpx>=0.27",
  "selectolax>=0.3.17",
  "beautifulsoup4>=4.12",
  "lxml>=5.2",
  "pydantic>=2.8",
  "transformers>=4.57",
  "sentencepiece>=0.2.1",
  "ctranslate2>=4.6.0",
  "tqdm>=4.66"
]

[project.scripts]
sagemtl = "sagemtl.cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
