"""HTML exporter for SageMTL."""

from __future__ import annotations

from typing import List

from .base import (
    BaseExporter,
    ExportCapability,
    ExportConfig,
    ExportResult,
    NovelData,
)


class HtmlExporter(BaseExporter):
    """Export novel to single-file HTML format.

    Features:
    - Self-contained HTML with embedded CSS
    - Navigation sidebar
    - Chapter anchors
    - Dark mode support
    """

    @classmethod
    def name(cls) -> str:
        return "HTML"

    @classmethod
    def extensions(cls) -> List[str]:
        return ["html", "htm"]

    @classmethod
    def capabilities(cls) -> ExportCapability:
        return (
            ExportCapability.COVER |
            ExportCapability.TOC |
            ExportCapability.METADATA |
            ExportCapability.STYLES |
            ExportCapability.IMAGES |
            ExportCapability.VOLUMES |
            ExportCapability.HYPERLINKS
        )

    def export(
        self,
        novel: NovelData,
        config: ExportConfig,
    ) -> ExportResult:
        """Export novel to HTML file."""
        output_path = self._get_output_path(novel, config)

        try:
            # Generate HTML content
            html_content = self._generate_html(novel, config)

            # Write file
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(html_content)

            return ExportResult.ok(output_path)

        except Exception as e:
            return ExportResult.failure(str(e))

    def _generate_html(self, novel: NovelData, config: ExportConfig) -> str:
        """Generate complete HTML document."""
        title = config.title or novel.title
        author = config.author or novel.author

        # Generate TOC
        toc_html = self._generate_toc(novel) if config.include_toc else ""

        # Generate chapters
        chapters_html = self._generate_chapters(novel, config)

        # Generate CSS
        css = self._get_css(config)

        # Generate JavaScript for navigation
        js = self._get_javascript()

        return f'''<!DOCTYPE html>
<html lang="{config.language}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{self._escape_html(title)}</title>
    <meta name="author" content="{self._escape_html(author)}">
    <meta name="description" content="{self._escape_html(novel.description or '')}">
    <meta name="generator" content="SageMTL">
    <style>
{css}
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <header class="header">
            <h1 class="title">{self._escape_html(title)}</h1>
            {f'<p class="author">by {self._escape_html(author)}</p>' if author else ''}
            <button class="theme-toggle" onclick="toggleTheme()" title="Toggle dark mode">
                <span class="theme-icon">🌙</span>
            </button>
        </header>

        <div class="main">
            <!-- Sidebar with TOC -->
            <aside class="sidebar">
                <button class="sidebar-toggle" onclick="toggleSidebar()">☰</button>
                {toc_html}
            </aside>

            <!-- Content -->
            <main class="content">
                {chapters_html}
            </main>
        </div>

        <!-- Footer -->
        <footer class="footer">
            <p>Generated by SageMTL</p>
        </footer>
    </div>

    <script>
{js}
    </script>
</body>
</html>'''

    def _generate_toc(self, novel: NovelData) -> str:
        """Generate table of contents HTML."""
        items = []
        current_volume = None

        for chapter in novel.chapters:
            # Volume header
            if chapter.volume_index is not None and chapter.volume_index != current_volume:
                current_volume = chapter.volume_index
                volume = next(
                    (v for v in novel.volumes if v.index == current_volume),
                    None
                )
                if volume:
                    items.append(
                        f'<li class="toc-volume">{self._escape_html(volume.title)}</li>'
                    )

            items.append(
                f'<li class="toc-chapter">'
                f'<a href="#chapter-{chapter.index}">{self._escape_html(chapter.title)}</a>'
                f'</li>'
            )

        return f'''
            <nav class="toc">
                <h2>Table of Contents</h2>
                <ul>
                    {''.join(items)}
                </ul>
            </nav>
        '''

    def _generate_chapters(self, novel: NovelData, config: ExportConfig) -> str:
        """Generate chapters HTML."""
        sections = []
        current_volume = None

        for chapter in novel.chapters:
            # Volume header
            if chapter.volume_index is not None and chapter.volume_index != current_volume:
                current_volume = chapter.volume_index
                volume = next(
                    (v for v in novel.volumes if v.index == current_volume),
                    None
                )
                if volume:
                    sections.append(f'''
                        <section class="volume" id="volume-{volume.index}">
                            <h2 class="volume-title">{self._escape_html(volume.title)}</h2>
                        </section>
                    ''')

            # Chapter
            content = chapter.html_content or self._text_to_html(chapter.content)
            sections.append(f'''
                <article class="chapter" id="chapter-{chapter.index}">
                    <h3 class="chapter-title">{self._escape_html(chapter.title)}</h3>
                    <div class="chapter-content">
                        {content}
                    </div>
                    <div class="chapter-nav">
                        {f'<a href="#chapter-{chapter.index - 1}" class="prev">← Previous</a>' if chapter.index > 1 else '<span></span>'}
                        <a href="#" class="top">↑ Top</a>
                        {f'<a href="#chapter-{chapter.index + 1}" class="next">Next →</a>' if chapter.index < len(novel.chapters) else '<span></span>'}
                    </div>
                </article>
            ''')

        return '\n'.join(sections)

    def _get_css(self, config: ExportConfig) -> str:
        """Generate CSS."""
        custom_css = config.custom_css or ""

        return f'''
:root {{
    --bg-color: #ffffff;
    --text-color: #333333;
    --link-color: #0066cc;
    --border-color: #e0e0e0;
    --sidebar-bg: #f5f5f5;
    --header-bg: #333333;
    --header-text: #ffffff;
}}

[data-theme="dark"] {{
    --bg-color: #1a1a1a;
    --text-color: #e0e0e0;
    --link-color: #66b3ff;
    --border-color: #444444;
    --sidebar-bg: #252525;
    --header-bg: #1a1a1a;
    --header-text: #ffffff;
}}

* {{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}}

body {{
    font-family: {config.font_family}, Georgia, serif;
    font-size: {config.font_size}pt;
    line-height: 1.7;
    background-color: var(--bg-color);
    color: var(--text-color);
    transition: background-color 0.3s, color 0.3s;
}}

.container {{
    max-width: 1400px;
    margin: 0 auto;
}}

/* Header */
.header {{
    background-color: var(--header-bg);
    color: var(--header-text);
    padding: 1.5rem 2rem;
    text-align: center;
    position: relative;
}}

.header .title {{
    font-size: 2rem;
    margin-bottom: 0.5rem;
}}

.header .author {{
    font-style: italic;
    opacity: 0.9;
}}

.theme-toggle {{
    position: absolute;
    right: 1rem;
    top: 50%;
    transform: translateY(-50%);
    background: transparent;
    border: none;
    color: var(--header-text);
    font-size: 1.5rem;
    cursor: pointer;
}}

/* Main layout */
.main {{
    display: flex;
}}

/* Sidebar */
.sidebar {{
    width: 280px;
    min-height: calc(100vh - 150px);
    background-color: var(--sidebar-bg);
    border-right: 1px solid var(--border-color);
    padding: 1rem;
    position: sticky;
    top: 0;
    overflow-y: auto;
    max-height: 100vh;
}}

.sidebar-toggle {{
    display: none;
    background: var(--sidebar-bg);
    border: 1px solid var(--border-color);
    padding: 0.5rem 1rem;
    cursor: pointer;
    font-size: 1.2rem;
}}

.toc h2 {{
    font-size: 1.2rem;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid var(--border-color);
}}

.toc ul {{
    list-style: none;
}}

.toc li {{
    margin: 0.3rem 0;
}}

.toc a {{
    color: var(--text-color);
    text-decoration: none;
    display: block;
    padding: 0.3rem 0.5rem;
    border-radius: 4px;
}}

.toc a:hover {{
    background-color: var(--border-color);
}}

.toc-volume {{
    font-weight: bold;
    margin-top: 1rem !important;
}}

.toc-chapter {{
    padding-left: 1rem;
}}

/* Content */
.content {{
    flex: 1;
    padding: 2rem;
    max-width: 800px;
}}

/* Volume */
.volume {{
    margin: 3rem 0;
    text-align: center;
}}

.volume-title {{
    font-size: 1.8rem;
    padding: 2rem 0;
    border-top: 2px solid var(--border-color);
    border-bottom: 2px solid var(--border-color);
}}

/* Chapter */
.chapter {{
    margin-bottom: 4rem;
}}

.chapter-title {{
    font-size: 1.4rem;
    margin-bottom: 1.5rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid var(--border-color);
}}

.chapter-content {{
    text-align: justify;
}}

.chapter-content p {{
    text-indent: 1.5em;
    margin: 0.8em 0;
}}

.chapter-nav {{
    display: flex;
    justify-content: space-between;
    margin-top: 2rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border-color);
}}

.chapter-nav a {{
    color: var(--link-color);
    text-decoration: none;
}}

.chapter-nav a:hover {{
    text-decoration: underline;
}}

/* Footer */
.footer {{
    text-align: center;
    padding: 1rem;
    border-top: 1px solid var(--border-color);
    font-size: 0.9rem;
    opacity: 0.7;
}}

/* Responsive */
@media (max-width: 900px) {{
    .main {{
        flex-direction: column;
    }}

    .sidebar {{
        width: 100%;
        position: relative;
        max-height: none;
        display: none;
    }}

    .sidebar.open {{
        display: block;
    }}

    .sidebar-toggle {{
        display: block;
        width: 100%;
    }}

    .content {{
        padding: 1rem;
    }}
}}

{custom_css}
'''

    def _get_javascript(self) -> str:
        """Generate JavaScript for interactivity."""
        return '''
function toggleTheme() {
    const html = document.documentElement;
    const currentTheme = html.getAttribute('data-theme');
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
    html.setAttribute('data-theme', newTheme);
    localStorage.setItem('theme', newTheme);

    const icon = document.querySelector('.theme-icon');
    icon.textContent = newTheme === 'dark' ? '☀️' : '🌙';
}

function toggleSidebar() {
    const sidebar = document.querySelector('.sidebar');
    sidebar.classList.toggle('open');
}

// Load saved theme
document.addEventListener('DOMContentLoaded', function() {
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme) {
        document.documentElement.setAttribute('data-theme', savedTheme);
        const icon = document.querySelector('.theme-icon');
        icon.textContent = savedTheme === 'dark' ? '☀️' : '🌙';
    }
});

// Smooth scroll for anchor links
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
            target.scrollIntoView({ behavior: 'smooth' });
        }
    });
});
'''
